Utils/Mockups: Add RUT generators and check digit calculator
magnet-cl/django-project-template pull request #114
Opened 2021-09-08 21:56 UTC by nstuardod

- Simplify the random RUT generator
- Decouple check digit computation from validation, so it can be used by the generator too.

2021-09-10 17:44 UTC, imunizaga requested changes

2021-09-10 17:44 UTC, imunizaga commented on base/utils.py
> +def rut_algorithm(rut):
El nombre "rut_algorithm" no explica qué es lo que hace este método.

2021-09-10 17:44 UTC, imunizaga commented on base/mockups.py
> +                         maximum_rut=99999999, **kwargs):
Kwargs no está siendo utilizado, así que no es necesario recibirlo.

2021-09-10 17:44 UTC, imunizaga commented on base/utils.py
> +def rut_check_digit(rut):
¿es necesario este método? no sé quién lo llamaría fuera de este módulo y tiene una sola línea y se llama solo por otro método

2021-09-13 15:49 UTC, nstuardod commented on base/utils.py
> +def rut_algorithm(rut):
Renombrado a `rut_mod11`

2021-09-13 15:50 UTC, nstuardod commented on base/mockups.py
> +                         maximum_rut=99999999, **kwargs):
Resuelto

2021-09-13 15:50 UTC, nstuardod commented on base/utils.py
> +def rut_check_digit(rut):
Tienes razón. Al momento solo se ocupa para convertir el mod11 a un carácter en el generador.

2021-09-13 15:56 UTC, imunizaga commented on base/utils.py
> +def rut_mod11(rut):
Alguien que no sabe que el dígito verificador del rut se calcula con un módulo de 11, no sabría qué se está obteniendo cuando se usa este método en otro lado. 

Creo que lo mejor sería cambiar este método para que retorne el dígito verificador en vez del módulo. Así puedes sacar esa lógica tanto de random_rut, como de validte_rut y además puede que le sirva a alguien más (creo que es difícil que alguien más use el módulo del rut pero si puede pasar que alguien use el dígito verificador para algo).

2021-09-13 16:28 UTC, nstuardod commented on base/utils.py
> +def rut_mod11(rut):
OK, entonces, ¿renombramos el método (`rut_check_digit`) o lo mantenemos tal cual?

2021-09-13 17:14 UTC, imunizaga commented on base/utils.py
> +def rut_mod11(rut):
Lo único malo de `rut_check_digit` es que  podría interpretarse como un método que "hace un check del dígito del rut" (porque check es un verbo en infinitivo), creo que me gustaría más `rut_verifying_digit` ¿qué opinas?

2021-09-13 17:30 UTC, nstuardod commented on base/utils.py
> +def rut_mod11(rut):
OK, se cambia entonces para evitar malentendidos.

2021-09-13 18:00 UTC, merged